# Generated by Django 4.0.4 on 2022-05-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_book_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='heat',
            field=models.IntegerField(default=0),
        ),
    ]
