# Generated by Django 4.0.4 on 2022-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_book_heat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('image', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=80)),
                ('actor', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('introduction', models.TextField(default='', max_length=1000)),
                ('score', models.DecimalField(decimal_places=1, max_digits=1)),
                ('heat', models.IntegerField(default=0)),
            ],
        ),
    ]
