# Generated by Django 4.0.4 on 2022-05-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tele',
            fields=[
                ('tele_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('image', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=80)),
                ('actor', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=1990)),
                ('introduction', models.TextField(default='', max_length=1000)),
                ('score', models.DecimalField(decimal_places=1, max_digits=1)),
                ('heat', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1990),
        ),
    ]
