# Generated by Django 4.0.4 on 2022-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_tele_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='column',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collect',
            name='resource_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collect',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
