# Generated by Django 4.0.4 on 2022-05-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0007_collect_column_collect_resource_id_collect_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('image', models.CharField(max_length=200)),
                ('heat', models.IntegerField(default=0)),
            ],
        ),
    ]
