# Generated by Django 4.0.4 on 2022-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('introduction', models.TextField(default='', max_length=1000)),
                ('heat', models.IntegerField(default=0)),
            ],
        ),
    ]
