# Generated by Django 4.0.4 on 2022-06-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='column',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='resource_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='score',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='tele',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
