# Generated by Django 4.0.4 on 2022-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_score_column_score_resource_id_score_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='tele',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
