# Generated by Django 4.0.4 on 2022-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0011_alter_book_score_alter_movie_score_alter_tele_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='id',
        ),
        migrations.AddField(
            model_name='score',
            name='score_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
