# Generated by Django 4.0.4 on 2022-06-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0013_alter_score_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='star',
        ),
    ]
