# Generated by Django 4.0.4 on 2022-06-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0014_rename_score_score_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='star',
            new_name='score',
        ),
    ]
