# Generated by Django 4.0.4 on 2022-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0015_rename_star_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='heat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='resource_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
