# Generated by Django 4.0.4 on 2022-06-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0016_article_author_id_article_column_article_heat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='article_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.IntegerField(default=0),
        ),
    ]
