# Generated by Django 3.2.5 on 2022-06-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0017_reply_article_id_reply_author_id_reply_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('resource_id', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
            ],
        ),
    ]
