# Generated by Django 3.2.5 on 2022-06-04 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0018_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Photos',
        ),
    ]
