# Generated by Django 4.0.4 on 2022-06-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0021_alter_score_score_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photo',
        ),
        migrations.AddField(
            model_name='photos',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
