# Generated by Django 4.0.4 on 2022-06-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0022_remove_photos_photo_photos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.IntegerField(default=0),
        ),
    ]
