# Generated by Django 3.2.5 on 2022-06-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0024_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('article_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
    ]
