# Generated by Django 4.0.4 on 2022-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0025_grouparticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.IntegerField(default=0),
        ),
    ]
