# Generated by Django 4.0.4 on 2022-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0026_group_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('manager_id', models.IntegerField(default=0)),
            ],
        ),
    ]
