# Generated by Django 4.0.4 on 2022-06-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0027_groupmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmanager',
            name='manager_id',
        ),
    ]
