# Generated by Django 3.2.12 on 2022-06-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0028_remove_groupmanager_manager_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('user_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
