# Generated by Django 4.0.4 on 2022-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0029_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerPicter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
