# Generated by Django 4.0.4 on 2022-06-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0030_innerpicter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InnerPicter',
        ),
    ]
