# Generated by Django 4.0.4 on 2022-06-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0031_delete_innerpicter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='level1_reply',
            field=models.IntegerField(default=0),
        ),
    ]
